### ISSUE TITLE
Install memory error

### ISSUE THREAD

**Issue by jacksun101** [respeaker/respeaker_python_library#14]
Can't install the pocketsphinx, please help.

root@ReSpeaker:~# pip install pocketsphinx --no-cache-dir
Collecting pocketsphinx
  Downloading pocketsphinx-0.1.3.zip (29.3MB)
    100% |################################| 29.3MB 1.4MB/s
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 488, in unzip_file
    data = zip.read(name)
  File "/usr/lib/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.7/zipfile.py", line 630, in read
    data = self.read1(n)
  File "/usr/lib/python2.7/zipfile.py", line 665, in read1
    data = self._fileobj.read(nbytes)
MemoryError

**Comment by jacksun101** [comment]
OK, I fixed it by restoring the firmware and firstboot it to factory default. And install the latest version of respeaker_python_library.
