### ISSUE TITLE
Respeaker mic array v2.0 DOA

### ISSUE THREAD

**Issue by maulikmadhavi** [respeaker/respeaker_python_library#45]
I am using respeaker microphone array v2.0 for DOA application in ubuntu. I was following the reference from http://wiki.seeedstudio.com/ReSpeaker_Mic_Array_v2.0/

1) during Update Firmware,  while running dfu.py I got ValueError. 

sudo python dfu.py --download 6_channels_firmware.bin  # The 6 channels version 
##
Traceback (most recent call last):
  File "dfu.py", line 229, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "dfu.py", line 218, in main
    dev = XMOS_DFU()
  File "dfu.py", line 198, in __init__
    super(XMOS_DFU, self).__init__()
  File "dfu.py", line 73, in __init__
    raise ValueError('No DFU device found')
ValueError: No DFU device found
###

2) Furthermore, while running doa.py, I got nothing. Also running separately following on python, dev variable is empty.

from tuning import Tuning
import usb.core
import usb.util
import time

dev = usb.core.find(idVendor=0x2886, idProduct=0x0018)

Please help me, thanks in advance.

**Comment by xiongyihui** [comment]
Do your computer recognize the usb sound card? You can use `lsusb` to check.

The usb mic array may already contains 6 channels firmware. You can use audacity to check how many channels does the sound card has.

**Comment by maulikmadhavi** [comment]
By running lsusb, I got: 

```
Bus 002 Device 002: ID 8087:8002 Intel Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:800a Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 007: ID 0424:5744 Standard Microsystems Corp. 
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 005: ID 046d:0a44 Logitech, Inc. Headset H390
Bus 003 Device 016: ID 0424:2744 Standard Microsystems Corp. 
Bus 003 Device 003: ID 413c:301a Dell Computer Corp. 
Bus 003 Device 002: ID 413c:2113 Dell Computer Corp. 
Bus 003 Device 017: ID 2886:0018  
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
The screenshot is attached for your reference,
![respeaker](https://user-images.githubusercontent.com/10569925/46779873-632e7e00-cd4c-11e8-84d9-2ad711775a87.jpg)
